"""
NetSentinel - Data Models
Defines structured data classes for network events, alerts, and analysis results.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


# ── Enums ──────────────────────────────────────────────────────

class Severity(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

    def __lt__(self, other):
        order = [Severity.LOW, Severity.MEDIUM, Severity.HIGH, Severity.CRITICAL]
        return order.index(self) < order.index(other)

    def __le__(self, other):
        return self == other or self.__lt__(other)


class AttackCategory(Enum):
    RECONNAISSANCE = "reconnaissance"
    BRUTE_FORCE = "brute_force"
    DDOS = "ddos"
    EXFILTRATION = "exfiltration"
    C2 = "c2"
    THREAT_INTEL = "threat_intel"
    EVASION = "evasion"
    INSIDER_THREAT = "insider_threat"
    ANONYMIZATION = "anonymization"
    ANOMALY = "anomaly"
    UNKNOWN = "unknown"


class Protocol(Enum):
    TCP = "TCP"
    UDP = "UDP"
    ICMP = "ICMP"
    HTTP = "HTTP"
    HTTPS = "HTTPS"
    DNS = "DNS"
    SSH = "SSH"
    FTP = "FTP"
    SMTP = "SMTP"
    OTHER = "OTHER"


class Direction(Enum):
    INBOUND = "inbound"
    OUTBOUND = "outbound"
    INTERNAL = "internal"
    UNKNOWN = "unknown"


# ── Data Classes ───────────────────────────────────────────────

@dataclass
class NetworkEvent:
    """Represents a single parsed network log entry."""
    timestamp: datetime
    src_ip: str
    dst_ip: str
    src_port: int
    dst_port: int
    protocol: str
    bytes_sent: int = 0
    bytes_received: int = 0
    packets: int = 1
    duration: float = 0.0
    flags: str = ""
    action: str = ""           # allow, deny, drop, failed, success
    status_code: Optional[int] = None
    direction: str = "unknown"
    domain: str = ""
    payload_size: int = 0
    raw_log: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def total_bytes(self) -> int:
        return self.bytes_sent + self.bytes_received

    def to_dict(self) -> Dict[str, Any]:
        return {
            "timestamp": self.timestamp.isoformat(),
            "src_ip": self.src_ip,
            "dst_ip": self.dst_ip,
            "src_port": self.src_port,
            "dst_port": self.dst_port,
            "protocol": self.protocol,
            "bytes_sent": self.bytes_sent,
            "bytes_received": self.bytes_received,
            "packets": self.packets,
            "duration": self.duration,
            "flags": self.flags,
            "action": self.action,
            "status_code": self.status_code,
            "direction": self.direction,
            "domain": self.domain,
            "total_bytes": self.total_bytes,
        }


@dataclass
class Alert:
    """Represents a security alert generated by the detection engine."""
    alert_id: str
    timestamp: datetime
    rule_id: str
    rule_name: str
    category: str
    severity: Severity
    src_ip: str
    dst_ip: str = ""
    dst_port: int = 0
    description: str = ""
    evidence: Dict[str, Any] = field(default_factory=dict)
    recommendation: str = ""
    false_positive_likelihood: str = "unknown"   # low, medium, high, unknown
    mitre_attack_id: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "alert_id": self.alert_id,
            "timestamp": self.timestamp.isoformat(),
            "rule_id": self.rule_id,
            "rule_name": self.rule_name,
            "category": self.category,
            "severity": self.severity.value,
            "src_ip": self.src_ip,
            "dst_ip": self.dst_ip,
            "dst_port": self.dst_port,
            "description": self.description,
            "evidence": self.evidence,
            "recommendation": self.recommendation,
            "false_positive_likelihood": self.false_positive_likelihood,
            "mitre_attack_id": self.mitre_attack_id,
        }


@dataclass
class TrafficStats:
    """Aggregated traffic statistics for a time window."""
    time_window_start: datetime
    time_window_end: datetime
    total_events: int = 0
    total_bytes: int = 0
    unique_src_ips: int = 0
    unique_dst_ips: int = 0
    unique_dst_ports: int = 0
    protocol_distribution: Dict[str, int] = field(default_factory=dict)
    top_talkers: List[Dict[str, Any]] = field(default_factory=list)
    top_destinations: List[Dict[str, Any]] = field(default_factory=list)
    top_ports: List[Dict[str, Any]] = field(default_factory=list)
    events_per_second: float = 0.0
    bytes_per_second: float = 0.0
    inbound_bytes: int = 0
    outbound_bytes: int = 0
    denied_connections: int = 0
    failed_actions: int = 0


@dataclass
class AnalysisResult:
    """Complete analysis result for a session."""
    analysis_id: str
    start_time: datetime
    end_time: datetime
    total_events_processed: int = 0
    total_files_processed: int = 0
    alerts: List[Alert] = field(default_factory=list)
    traffic_stats: Optional[TrafficStats] = None
    risk_score: float = 0.0          # 0-100 overall risk score
    summary: str = ""
    recommendations: List[str] = field(default_factory=list)
    processing_time_seconds: float = 0.0

    @property
    def alert_count_by_severity(self) -> Dict[str, int]:
        counts = {"LOW": 0, "MEDIUM": 0, "HIGH": 0, "CRITICAL": 0}
        for alert in self.alerts:
            counts[alert.severity.value] = counts.get(alert.severity.value, 0) + 1
        return counts

    @property
    def risk_level(self) -> str:
        if self.risk_score >= 80:
            return "CRITICAL"
        elif self.risk_score >= 60:
            return "HIGH"
        elif self.risk_score >= 40:
            return "MEDIUM"
        else:
            return "LOW"
